version: '3.8'

services:
  http-server:
    image: likhith2005/test-multistage-golang:http-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080

  ws-server:
    image: likhith2005/test-multistage-golang:ws-server
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - PORT=8081

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - http-server
      - ws-server
    restart: unless-stopped 