version: '3.8'

services:
  http-server:
    build:
      context: .
      dockerfile: ./cmd/http-server/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  ws-server:
    build:
      context: .
      dockerfile: ./cmd/ws-server/Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - http-server
      - ws-server
    restart: unless-stopped